import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

component AddRepsButton inherits TouchArea {
    in property <int> rep-increment;

    container := Rectangle {
        height: 24px;
        width: 24px;
        border-radius: 4px;
        background: #000000;

        HorizontalLayout {
            padding: 4px;

            rep-text := Text {
                text: "+" + rep-increment;
                color: #FFFFFF;
                font-size: 20px;
            }
        }
    }

    states [
        pressed when root.pressed: {
            container.background: #777777;
            rep-text.color: #000000;
        }
    ]
}

component CaliCounter inherits Rectangle {
    callback add-reps(int);

    in property <string> workout-name;
    in property <int> rep-count;

    height: 24px;

    HorizontalBox {
        padding: 5px;
        alignment: space-between;

        Text {
            text: workout-name;
            preferred-width: 50px;
        }

        Text {
            text: rep-count;
        }

        private property <[int]> rep-increments: [1, 3, 5, 10];

        for increment in rep-increments: AddRepsButton {
            rep-increment: increment;
            clicked => {
                root.add-reps(increment);
            }
        }
    }
}

export component AppWindow inherits Window {
    VerticalBox {
        CaliCounter {
            workout-name: "Pushups";
        }

        CaliCounter {
            workout-name: "Situps";
        }

        CaliCounter {
            workout-name: "Pullups";
        }
    }
}
